# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bledata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('researcherid', models.IntegerField(blank=True, null=True)),
                ('clocktimedifference', models.DurationField(blank=True, null=True)),
                ('_pcap', models.TextField(blank=True, db_column='data')),
            ],
            options={
                'verbose_name_plural': 'bledatas',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('researcherid', models.IntegerField(blank=True, null=True)),
                ('clocktimedifference', models.DurationField(blank=True, null=True)),
                ('eventtype', models.CharField(blank=True, max_length=1024)),
                ('event', models.TextField(blank=True)),
                ('codereference', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('researcherid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'experiments',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(default='{"admin": false, "researcher": false, "subject": true}', max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('educationlevel', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('researcherid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.Experiment')),
            ],
            options={
                'verbose_name_plural': 'runs',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='runid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.Run'),
        ),
        migrations.AddField(
            model_name='bledata',
            name='runid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Run'),
        ),
    ]
