# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bledata',
            name='runid',
        ),
        migrations.RemoveField(
            model_name='event',
            name='runid',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='run',
            name='experiment',
        ),
        migrations.DeleteModel(
            name='Bledata',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Run',
        ),
    ]
