# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_auto_20171013_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvalue', models.FloatField()),
                ('level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000)),
                ('enrichments', models.ManyToManyField(blank=True, related_name='children', to='api.Enrichment')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneid', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termid', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=10000)),
                ('namespace', models.CharField(blank=True, max_length=10000)),
                ('definition', models.CharField(blank=True, max_length=10000)),
                ('synonym', models.CharField(blank=True, max_length=1000)),
                ('parents', models.ManyToManyField(blank=True, related_name='_term_parents_+', to='api.Term')),
            ],
        ),
        migrations.AddField(
            model_name='gene',
            name='terms',
            field=models.ManyToManyField(blank=True, related_name='genes', to='api.Term'),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Term'),
        ),
    ]
