# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171028_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='termid',
            field=models.CharField(max_length=100),
        ),
    ]
