# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171028_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='termid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
