# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171028_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='semanticdissimilarityx',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='semanticdissimilarityy',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
