# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_run_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='enrichments',
            field=models.ManyToManyField(blank=True, related_name='enrichments', to='api.Enrichment'),
        ),
    ]
