# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171116_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='terms',
        ),
        migrations.AddField(
            model_name='enrichment',
            name='cluster',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='genes',
            field=models.ManyToManyField(blank=True, related_name='enrichments', to='api.Term'),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='metoid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrichment',
            name='semanticdissimilarityx',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrichment',
            name='semanticdissimilarityy',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
