# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171219_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrichment',
            old_name='metoid',
            new_name='medoid',
        ),
    ]
