# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171219_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichment',
            name='semanticdissimilarityx',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='enrichment',
            name='semanticdissimilarityy',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
