# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171219_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichment',
            name='genes',
            field=models.ManyToManyField(blank=True, related_name='enrichments', to='api.Gene'),
        ),
    ]
