# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20171220_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='geneid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
