# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171220_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='ip',
            field=models.CharField(blank=True, default='127.0.0.1', max_length=1000),
        ),
    ]
