# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_run_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='term',
            name='termid',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='term',
            name='ontology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='api.Ontology'),
            preserve_default=False,
        ),
    ]
