# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180216_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontology',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
