# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_ontology_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontology',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
