# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190225_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='api.Term'),
        ),
    ]
